apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: v04ks9fcg-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/v04ks9fcg-dotnet-basic-gitops